[package]
name = "tictacchess"
version = "0.1.0"
authors = ["charlyalizadeh <charlypro1502@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14.0"
nalgebra = "0.24.1"
rand = "0.8.3"
